<?php

namespace Proxies\__CG__\Transporte\TransporteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Poliza extends \Transporte\TransporteBundle\Entity\Poliza implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Poliza' . "\0" . 'id', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Poliza' . "\0" . 'fechaAlta', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Poliza' . "\0" . 'vencimiento', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Poliza' . "\0" . 'nroPoliza', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Poliza' . "\0" . 'detalleCobertura', 'aseguradora', 'vehiculo');
        }

        return array('__isInitialized__', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Poliza' . "\0" . 'id', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Poliza' . "\0" . 'fechaAlta', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Poliza' . "\0" . 'vencimiento', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Poliza' . "\0" . 'nroPoliza', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Poliza' . "\0" . 'detalleCobertura', 'aseguradora', 'vehiculo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Poliza $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', array());

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function getVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVencimiento', array());

        return parent::getVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function getNroPoliza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroPoliza', array());

        return parent::getNroPoliza();
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalleCobertura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalleCobertura', array());

        return parent::getDetalleCobertura();
    }

    /**
     * {@inheritDoc}
     */
    public function getAseguradora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAseguradora', array());

        return parent::getAseguradora();
    }

    /**
     * {@inheritDoc}
     */
    public function getVehiculo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehiculo', array());

        return parent::getVehiculo();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', array($fechaAlta));

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function setVencimiento($vencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVencimiento', array($vencimiento));

        return parent::setVencimiento($vencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function setNroPoliza($nroPoliza)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNroPoliza', array($nroPoliza));

        return parent::setNroPoliza($nroPoliza);
    }

    /**
     * {@inheritDoc}
     */
    public function setDetalleCobertura($detalleCobertura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetalleCobertura', array($detalleCobertura));

        return parent::setDetalleCobertura($detalleCobertura);
    }

    /**
     * {@inheritDoc}
     */
    public function setAseguradora($aseguradora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAseguradora', array($aseguradora));

        return parent::setAseguradora($aseguradora);
    }

    /**
     * {@inheritDoc}
     */
    public function setVehiculo($vehiculo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehiculo', array($vehiculo));

        return parent::setVehiculo($vehiculo);
    }

}
