<?php

namespace Proxies\__CG__\Transporte\TransporteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contrato extends \Transporte\TransporteBundle\Entity\Contrato implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Contrato' . "\0" . 'id', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Contrato' . "\0" . 'fechaAlta', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Contrato' . "\0" . 'fechaBaja', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Contrato' . "\0" . 'expediente', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Contrato' . "\0" . 'movil', 'tipoServicio', 'vehiculo', 'empresa', 'decreto', 'inspeccionesMecanicas');
        }

        return array('__isInitialized__', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Contrato' . "\0" . 'id', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Contrato' . "\0" . 'fechaAlta', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Contrato' . "\0" . 'fechaBaja', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Contrato' . "\0" . 'expediente', '' . "\0" . 'Transporte\\TransporteBundle\\Entity\\Contrato' . "\0" . 'movil', 'tipoServicio', 'vehiculo', 'empresa', 'decreto', 'inspeccionesMecanicas');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contrato $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', array());

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaBaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaBaja', array());

        return parent::getFechaBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function getExpediente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpediente', array());

        return parent::getExpediente();
    }

    /**
     * {@inheritDoc}
     */
    public function getMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovil', array());

        return parent::getMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoServicio', array());

        return parent::getTipoServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function getVehiculo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehiculo', array());

        return parent::getVehiculo();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function getDecreto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecreto', array());

        return parent::getDecreto();
    }

    /**
     * {@inheritDoc}
     */
    public function getInspeccionesMecanicas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInspeccionesMecanicas', array());

        return parent::getInspeccionesMecanicas();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', array($fechaAlta));

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaBaja($fechaBaja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaBaja', array($fechaBaja));

        return parent::setFechaBaja($fechaBaja);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpediente($expediente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpediente', array($expediente));

        return parent::setExpediente($expediente);
    }

    /**
     * {@inheritDoc}
     */
    public function setMovil($movil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMovil', array($movil));

        return parent::setMovil($movil);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoServicio($tipoServicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoServicio', array($tipoServicio));

        return parent::setTipoServicio($tipoServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function setVehiculo($vehiculo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehiculo', array($vehiculo));

        return parent::setVehiculo($vehiculo);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa($empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function setDecreto($decreto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDecreto', array($decreto));

        return parent::setDecreto($decreto);
    }

    /**
     * {@inheritDoc}
     */
    public function setInspeccionesMecanicas($inspeccionesMecanicas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInspeccionesMecanicas', array($inspeccionesMecanicas));

        return parent::setInspeccionesMecanicas($inspeccionesMecanicas);
    }

}
